# Use postgres/example user/password credentials
volumes:
  chatterbox_data: {}
  redis_data: {}

services:
  db:
    image: pgvector/pgvector:pg17 # postgres with pgvector extension
    restart: always
    volumes:
      - chatterbox_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # temporal:
  #   image: temporalio/auto-setup:1.21
  #   ports:
  #     - "7233:7233"
  #   environment:
  #     DB: postgresql
  #     DB_PORT: 5432
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PWD: ${DB_PASSWORD}
  #     POSTGRES_SEEDS: db
  #   depends_on:
  #     - db
  #   restart: always

  # temporal-ui:
  #   image: temporalio/ui:latest
  #   ports:
  #     - "8233:8080"
  #   environment:
  #     TEMPORAL_ADDRESS: temporal:7233
  #   depends_on:
  #     - temporal
