# Use postgres/example user/password credentials
volumes:
  chatterbox_data:

services:
  db:
    image: pgvector/pgvector:pg17 # postgres with pgvector extension
    restart: always
    volumes:
      - chatterbox_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - 5432:5432
